output "ec2_public_ip" {
  description = "Public IP of the EC2 K3s node"
  value       = module.compute.public_ip
}

output "cloudfront_streaming_url" {
  description = "Domain name of CloudFront CDN"
  value       = module.cdn.cloudfront_domain_name
}

output "private_key" {
  description = "Dynamic SSH Private Key generated by TLS provider"
  value       = module.compute.private_key_pem
  sensitive   = true
}